# Generated by Django 5.0.3 on 2026-04-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0002_prescriptionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionrequest',
            name='lab_report',
            field=models.FileField(blank=True, help_text='Upload your lab report (PDF/Image)', null=True, upload_to='lab_reports/'),
        ),
    ]
